### ISSUE TITLE
Refund?

### ISSUE THREAD

**Issue by dsignr** [designmodo/Flat-UI-Pro-Support#520]
Hi, I am not satisfied with the Flat UI pro:

1) I have already purchased it for another client last november and have used it back then.
2) This time I purchased it for another client after almost a year and still the code hasn't changed much, it's not even maintained anymore? Last modified date in your code seems to be November 2014. Can I get a refund please, I'm not comfortable using this for my client.

Thank you.

**Comment by MonsterCritic** [comment]
Hey dsignr,

Please, use our contact form: http://designmodo.com/contact-us/

**Comment by ottz0** [comment]
Yes...totally dropped from the radar..
