### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by 123dj** [designmodo/Flat-UI-Pro-Support#521]
The icons, both functional (checkboxes) and user-defined (social icons) are not working for me.  I downloaded the latest Flat UI Pro version and threw everything from the `dist/` folder onto my server (I'm using [Meteor](http://meteor.com), so any CSS or JS file I put in my project's `client/` directory will get served to the browser).

**Safari 8.0.7**:
![screen shot 2015-06-25 at 18 04 18](https://cloud.githubusercontent.com/assets/7410405/8367523/ac35de88-1b64-11e5-8664-bc0517c690ca.png)
(Bottom footer icons)

![screen shot 2015-06-25 at 18 03 50](https://cloud.githubusercontent.com/assets/7410405/8367519/a68964d2-1b64-11e5-924f-cd394e6dda2b.png)
(Checkboxes)

**Firefox 38.0.1**:
![screen shot 2015-06-25 at 18 05 51](https://cloud.githubusercontent.com/assets/7410405/8367552/f7d07a6a-1b64-11e5-9986-68e32dd9e4e8.png)
(Bottom footer icons)

![screen shot 2015-06-25 at 18 05 41](https://cloud.githubusercontent.com/assets/7410405/8367574/4805f2b2-1b65-11e5-863a-672bea6208b3.png)
(Checkboxes)

I'm on OS X 10.10.4, if that matters.  Thanks.

**Comment by MonsterCritic** [comment]
When local HTML files (e.g., those located on your hard drive) are loaded into the browser (Firefox), the scripts and links within have restrictions on what they can see and do. Those restrictions are determined by the same-origin policy for local files, which this preference controls. To turn off it go to **about:config** > **security.fileuri.strict_origin_policy** and set **false**

**Comment by 123dj** [comment]
Still not working:
![screen shot 2015-06-26 at 11 06 06](https://cloud.githubusercontent.com/assets/7410405/8381779/71e411a2-1bf3-11e5-9cdc-fafafd748bb0.png)

![screen shot 2015-06-26 at 11 06 28](https://cloud.githubusercontent.com/assets/7410405/8381782/793f1ef6-1bf3-11e5-995b-e9a8d810d06e.png)

**Comment by MonsterCritic** [comment]
Anyway, it's not because of Flat UI, this is causing by Firefox origin policy. On my computer it was fixed by changing the parameter above.

**Comment by 123dj** [comment]
Can you check it [here](http://104.219.54.18/signup) with your current setup?  I deployed to a live server.

**Comment by MonsterCritic** [comment]
Doesn't work for me :( http://cl.ly/bnNx (Chrome, Mac)

**Comment by 123dj** [comment]
Hmm... do you have any ideas on what could be wrong?  Is the font file corrupted, and/or my server setup messing it up?

**Comment by MonsterCritic** [comment]
No ideas. Never seen that before. Just attach it as static files, do not compress or modify them.

**Comment by 123dj** [comment]
Finally got it, yay!  I had to put all of Flat UI in Meteor's `public` folder.  Apparently when files are in `client/` Meteor modifies them too much for browsers' liking.  Thanks for your help.
